---
title: "Détermination des critères de sexage de *Varanus salvator*"
author: "Baire Alexia, Spagna Camille, Curto Jeanne, Hallot Lou"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
---

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport en 5-6 phrases.-->

Le but de ce projet est de déterminer le sexe des *Varanus salvator* à partir de mesures morphométriques diverses. Cependant, les mesures effectuées sont prises sur des varans issus de l'élevage à des fins de commerce de peau. Ces usines ont tendance à accepter des individus de moins de 5 kilos. Cela ne représente donc peut-être pas les conditions naturelles de détermination de sexe.

## But

<!--% Rédigez le but de ce rapport en 2 phrases.-->

Le but de ce projet est de déterminer le sexe des *Varanus salvator* à partir de mesures morphométriques diverses.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter les données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

Au cours de ce projet, l'analyse des *Varanus Salvator* va être réalisée. Le jeu de donnée a été trouvé sur le site [Nature](https://www.nature.com/) dans la section Scientific data. Il comporte 146 individus et 20 variables. Plus amples informations sur ce jeu de données ont été trouvées au sein de [@alymann2024].

L'analyse est réalisée avec le logiciel R (`r R.version.string`) et en particulier le package {modelit} version `r packageVersion("modelit")` avec la [SciViews Box 2025](https://www.sciviews.org/software/svbox/) dans [Saturn Cloud](https://saturncloud.io/) (Linux Ubuntu 22.04). Le seuil $\alpha$ de tous les tests est fixé à l'avance à 5%.

## Résultats

<!--% Présentez les deux modèles les plus pertinents que vous avez sélectionnés. Structurez la section en deux parties avec deux titres de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->

Les mâles de *Varanus salvator* présentent une queue plus longue et plus large et un crâne légèrement plus grand que les femelles, bien que des chevauchements existent entre individus.

La circonférence relative de la queue et la longueur de la queue par rapport à la longueur totale sont des indicateurs fiables pour prédire le sexe.

L’inclusion des mesures du crâne, et notamment l’interaction entre largeur et longueur du crâne, peut améliorer légèrement la précision des modèles de prédiction.

Enfin, nou savons décidé de conserver les 2 modèles linéaires génaralisés car ceux-ci sont les plus pertinents.

## Bibliographie
